EVENT_TAGS = [
    # Corporate Actions
    {"filter_name": "Merger Announced", "tag": "Merger", "category": "Corporate Actions"},
    {"filter_name": "Acquisition Announced", "tag": "Acquisition", "category": "Corporate Actions"},
    {"filter_name": "Buyout / Takeover", "tag": "Buyout", "category": "Corporate Actions"},
    {"filter_name": "Spin-Off Announced", "tag": "Spin-Off", "category": "Corporate Actions"},
    {"filter_name": "Divestiture / Asset Sale", "tag": "Divestiture", "category": "Corporate Actions"},
    {"filter_name": "IPO Announced", "tag": "IPO", "category": "Corporate Actions"},
    {"filter_name": "Delisting Notice", "tag": "Delisting", "category": "Corporate Actions"},
    {"filter_name": "Strategic Review Initiated", "tag": "Strategic Review", "category": "Corporate Actions"},
    {"filter_name": "Business Restructuring", "tag": "Restructuring", "category": "Corporate Actions"},
    {"filter_name": "Asset Impairment Recorded", "tag": "Impairment", "category": "Corporate Actions"},
    {"filter_name": "Reverse Stock Split", "tag": "Reverse Split", "category": "Corporate Actions"},
    {"filter_name": "Stock Split Announced", "tag": "Stock Split", "category": "Corporate Actions"},
    {"filter_name": "Going Private Transaction", "tag": "Going Private", "category": "Corporate Actions"},
    {"filter_name": "Change in Control", "tag": "Change of Control", "category": "Corporate Actions"},

    # Earnings & Financial Results
    {"filter_name": "Earnings Beat Expectations", "tag": "Earnings Beat", "category": "Earnings & Financial Results"},
    {"filter_name": "Earnings Miss Expectations", "tag": "Earnings Miss", "category": "Earnings & Financial Results"},
    {"filter_name": "Earnings Inline with Estimates", "tag": "Earnings Inline", "category": "Earnings & Financial Results"},
    {"filter_name": "Earnings Pre-Announcement", "tag": "Earnings Prelim", "category": "Earnings & Financial Results"},
    {"filter_name": "Earnings Restatement Issued", "tag": "Earnings Restated", "category": "Earnings & Financial Results"},
    {"filter_name": "Revenue Growth Reported", "tag": "Revenue Growth", "category": "Earnings & Financial Results"},
    {"filter_name": "Revenue Decline Reported", "tag": "Revenue Decline", "category": "Earnings & Financial Results"},
    {"filter_name": "Margin Expansion Reported", "tag": "Margin Expansion", "category": "Earnings & Financial Results"},
    {"filter_name": "Margin Compression Reported", "tag": "Margin Compression", "category": "Earnings & Financial Results"},
    {"filter_name": "Cash Flow Improvement", "tag": "Cash Flow Up", "category": "Earnings & Financial Results"},
    {"filter_name": "Cash Flow Deterioration", "tag": "Cash Flow Down", "category": "Earnings & Financial Results"},
    {"filter_name": "Operating Income Growth", "tag": "Operating Income Up", "category": "Earnings & Financial Results"},
    {"filter_name": "Operating Income Decline", "tag": "Operating Income Down", "category": "Earnings & Financial Results"},
    {"filter_name": "Cost Reduction Program Announced", "tag": "Cost Reduction", "category": "Earnings & Financial Results"},
    {"filter_name": "Cost Inflation Pressure", "tag": "Cost Pressure", "category": "Earnings & Financial Results"},

    # Guidance & Outlook
    {"filter_name": "Guidance Raised", "tag": "Guidance Raised", "category": "Guidance & Outlook"},
    {"filter_name": "Guidance Cut", "tag": "Guidance Cut", "category": "Guidance & Outlook"},
    {"filter_name": "Guidance Issued", "tag": "Guidance Issued", "category": "Guidance & Outlook"},
    {"filter_name": "Guidance Reaffirmed", "tag": "Guidance Reaffirmed", "category": "Guidance & Outlook"},
    {"filter_name": "Long-Term Outlook Updated", "tag": "Outlook Updated", "category": "Guidance & Outlook"},
    {"filter_name": "Outlook Withdrawn", "tag": "Outlook Withdrawn", "category": "Guidance & Outlook"},
    {"filter_name": "Forecast Change Announced", "tag": "Forecast Change", "category": "Guidance & Outlook"},
    {"filter_name": "Demand Outlook Change", "tag": "Demand Outlook", "category": "Guidance & Outlook"},
    {"filter_name": "Macro Sensitivity Warning", "tag": "Macro Warning", "category": "Guidance & Outlook"},
    {"filter_name": "Capital Expenditure Outlook Change", "tag": "CapEx Outlook", "category": "Guidance & Outlook"},

    # Capital Allocation
    {"filter_name": "Dividend Declared", "tag": "Dividend Declared", "category": "Capital Allocation"},
    {"filter_name": "Dividend Increase Announced", "tag": "Dividend Increase", "category": "Capital Allocation"},
    {"filter_name": "Dividend Cut Announced", "tag": "Dividend Cut", "category": "Capital Allocation"},
    {"filter_name": "Share Buyback Announced", "tag": "Buyback Announced", "category": "Capital Allocation"},
    {"filter_name": "Share Buyback Expansion", "tag": "Buyback Expanded", "category": "Capital Allocation"},
    {"filter_name": "Share Buyback Suspension", "tag": "Buyback Suspended", "category": "Capital Allocation"},
    {"filter_name": "Debt Issuance Announced", "tag": "Debt Issuance", "category": "Capital Allocation"},
    {"filter_name": "Debt Reduction Announced", "tag": "Debt Reduction", "category": "Capital Allocation"},
    {"filter_name": "Equity Capital Raise", "tag": "Equity Raise", "category": "Capital Allocation"},
    {"filter_name": "Convertible Debt Issuance", "tag": "Convertible Debt", "category": "Capital Allocation"},
    {"filter_name": "Credit Facility Update", "tag": "Credit Facility", "category": "Capital Allocation"},
    {"filter_name": "Leverage Target Change", "tag": "Leverage Change", "category": "Capital Allocation"},

    # Legal & Regulatory
    {"filter_name": "SEC Filing Submitted", "tag": "SEC Filing", "category": "Legal & Regulatory"},
    {"filter_name": "SEC Investigation Announced", "tag": "SEC Investigation", "category": "Legal & Regulatory"},
    {"filter_name": "DOJ Investigation Announced", "tag": "DOJ Investigation", "category": "Legal & Regulatory"},
    {"filter_name": "Lawsuit Filed", "tag": "Lawsuit", "category": "Legal & Regulatory"},
    {"filter_name": "Legal Settlement Reached", "tag": "Settlement", "category": "Legal & Regulatory"},
    {"filter_name": "Antitrust Action Initiated", "tag": "Antitrust Action", "category": "Legal & Regulatory"},
    {"filter_name": "Regulatory Approval Granted", "tag": "Regulatory Approval", "category": "Legal & Regulatory"},
    {"filter_name": "Regulatory Approval Denied", "tag": "Regulatory Rejection", "category": "Legal & Regulatory"},
    {"filter_name": "Compliance Violation Disclosed", "tag": "Compliance Violation", "category": "Legal & Regulatory"},
    {"filter_name": "Fine or Penalty Issued", "tag": "Fine / Penalty", "category": "Legal & Regulatory"},
    {"filter_name": "Consent Decree Issued", "tag": "Consent Decree", "category": "Legal & Regulatory"},
    {"filter_name": "Licensing Risk Identified", "tag": "Licensing Risk", "category": "Legal & Regulatory"},
    {"filter_name": "Sanctions Exposure Identified", "tag": "Sanctions Risk", "category": "Legal & Regulatory"},
]
