EVENT_TAGS = [
    # Corporate Actions
    {"filter_name": "Merger Announced", "tag": "Merger", "category": "Corporate Actions", "keywords": ["merger", "merge", "merging", "business combination"]},
    {"filter_name": "Acquisition Announced", "tag": "Acquisition", "category": "Corporate Actions", "keywords": ["acquisition", "acquire", "acquired", "buying", "bought", "takeover"]},
    {"filter_name": "Buyout / Takeover", "tag": "Buyout", "category": "Corporate Actions", "keywords": ["buyout", "takeover", "go private", "going private", "tender offer"]},
    {"filter_name": "Spin-Off Announced", "tag": "Spin-Off", "category": "Corporate Actions", "keywords": ["spin-off", "spinoff", "spin off", "demerger", "separate public company"]},
    {"filter_name": "Divestiture / Asset Sale", "tag": "Divestiture", "category": "Corporate Actions", "keywords": ["divestiture", "divest", "asset sale", "selling assets", "sold its"]},
    {"filter_name": "IPO Announced", "tag": "IPO", "category": "Corporate Actions", "keywords": ["ipo", "initial public offering", "public listing", "going public", "list on nyse", "list on nasdaq"]},
    {"filter_name": "Delisting Notice", "tag": "Delisting", "category": "Corporate Actions", "keywords": ["delisting", "delist", "non-compliance", "deficiency notice"]},
    {"filter_name": "Strategic Review Initiated", "tag": "Strategic Review", "category": "Corporate Actions", "keywords": ["strategic review", "exploring strategic alternatives", "evaluating options", "sale of the company"]},
    {"filter_name": "Business Restructuring", "tag": "Restructuring", "category": "Corporate Actions", "keywords": ["restructuring", "reorganization", "job cuts", "layoffs", "reduce workforce"]},
    {"filter_name": "Asset Impairment Recorded", "tag": "Impairment", "category": "Corporate Actions", "keywords": ["impairment", "write-down", "write-off", "goodwill impairment"]},
    {"filter_name": "Reverse Stock Split", "tag": "Reverse Split", "category": "Corporate Actions", "keywords": ["reverse stock split", "reverse split", "consolidation of shares"]},
    {"filter_name": "Stock Split Announced", "tag": "Stock Split", "category": "Corporate Actions", "keywords": ["stock split", "share split", "forward split"]},
    {"filter_name": "Going Private Transaction", "tag": "Going Private", "category": "Corporate Actions", "keywords": ["going private", "privatization", "take private"]},
    {"filter_name": "Change in Control", "tag": "Change of Control", "category": "Corporate Actions", "keywords": ["change in control", "new majority owner", "activist investor"]},

    # Earnings & Financial Results
    {"filter_name": "Earnings Beat Expectations", "tag": "Earnings Beat", "category": "Earnings & Financial Results", "keywords": ["beat estimates", "topped estimates", "surpassed estimates", "exceeded estimates", "beat consensus", "topped consensus"]},
    {"filter_name": "Earnings Miss Expectations", "tag": "Earnings Miss", "category": "Earnings & Financial Results", "keywords": ["missed estimates", "missed consensus", "earnings miss", "revenue miss", "sales miss", "missed expectations"]},
    {"filter_name": "Earnings Inline with Estimates", "tag": "Earnings Inline", "category": "Earnings & Financial Results", "keywords": ["inline with estimates", "matched estimates", "matched consensus", "in line with expectations"]},
    {"filter_name": "Earnings Pre-Announcement", "tag": "Earnings Prelim", "category": "Earnings & Financial Results", "keywords": ["preliminary results", "pre-announce", "preannouncement"]},
    {"filter_name": "Earnings Restatement Issued", "tag": "Earnings Restated", "category": "Earnings & Financial Results", "keywords": ["restatement", "restate financials", "accounting error", "material weakness"]},
    {"filter_name": "Revenue Growth Reported", "tag": "Revenue Growth", "category": "Earnings & Financial Results", "keywords": ["revenue growth", "sales up", "revenue increased", "sales jump"]},
    {"filter_name": "Revenue Decline Reported", "tag": "Revenue Decline", "category": "Earnings & Financial Results", "keywords": ["revenue decline", "sales down", "revenue fell", "sales drop"]},
    {"filter_name": "Margin Expansion Reported", "tag": "Margin Expansion", "category": "Earnings & Financial Results", "keywords": ["margin expansion", "margins improved", "gross margin up", "operating margin increase"]},
    {"filter_name": "Margin Compression Reported", "tag": "Margin Compression", "category": "Earnings & Financial Results", "keywords": ["margin compression", "margins contracted", "gross margin down", "operating margin decrease"]},
    {"filter_name": "Cash Flow Improvement", "tag": "Cash Flow Up", "category": "Earnings & Financial Results", "keywords": ["cash flow positive", "free cash flow increase", "cash generation"]},
    {"filter_name": "Cash Flow Deterioration", "tag": "Cash Flow Down", "category": "Earnings & Financial Results", "keywords": ["cash burn", "negative cash flow", "cash flow decrease"]},
    {"filter_name": "Operating Income Growth", "tag": "Operating Income Up", "category": "Earnings & Financial Results", "keywords": ["operating income growth", "operating profit up"]},
    {"filter_name": "Operating Income Decline", "tag": "Operating Income Down", "category": "Earnings & Financial Results", "keywords": ["operating income decline", "operating profit down"]},
    {"filter_name": "Cost Reduction Program Announced", "tag": "Cost Reduction", "category": "Earnings & Financial Results", "keywords": ["cost reduction", "cost savings", "cutting costs", "expense reduction"]},
    {"filter_name": "Cost Inflation Pressure", "tag": "Cost Pressure", "category": "Earnings & Financial Results", "keywords": ["inflationary pressure", "higher input costs", "rising costs"]},

    # Guidance & Outlook
    {"filter_name": "Guidance Raised", "tag": "Guidance Raised", "category": "Guidance & Outlook", "keywords": ["raised guidance", "guidance hike", "outlook upgrade", "raises outlook", "lifts guidance"]},
    {"filter_name": "Guidance Cut", "tag": "Guidance Cut", "category": "Guidance & Outlook", "keywords": ["lowered guidance", "cut guidance", "outlook downgrade", "cuts outlook", "lowers guidance"]},
    {"filter_name": "Guidance Issued", "tag": "Guidance Issued", "category": "Guidance & Outlook", "keywords": ["issued guidance", "provides outlook", "initial guidance"]},
    {"filter_name": "Guidance Reaffirmed", "tag": "Guidance Reaffirmed", "category": "Guidance & Outlook", "keywords": ["reaffirmed guidance", "outlook valid", "maintains guidance"]},
    {"filter_name": "Long-Term Outlook Updated", "tag": "Outlook Updated", "category": "Guidance & Outlook", "keywords": ["long-term outlook", "strategic plan update", "5-year plan"]},
    {"filter_name": "Outlook Withdrawn", "tag": "Outlook Withdrawn", "category": "Guidance & Outlook", "keywords": ["withdrew guidance", "pulling guidance", "suspended outlook"]},
    {"filter_name": "Forecast Change Announced", "tag": "Forecast Change", "category": "Guidance & Outlook", "keywords": ["forecast adjustment", "updated forecast"]},
    {"filter_name": "Demand Outlook Change", "tag": "Demand Outlook", "category": "Guidance & Outlook", "keywords": ["demand softening", "demand strengthening", "order book"]},
    {"filter_name": "Macro Sensitivity Warning", "tag": "Macro Warning", "category": "Guidance & Outlook", "keywords": ["macro headwinds", "economic uncertainty"]},
    {"filter_name": "Capital Expenditure Outlook Change", "tag": "CapEx Outlook", "category": "Guidance & Outlook", "keywords": ["capex increase", "capex cut", "capital spending plan"]},

    # Capital Allocation
    {"filter_name": "Dividend Declared", "tag": "Dividend Declared", "category": "Capital Allocation", "keywords": ["declared dividend", "dividend payout", "cash dividend"]},
    {"filter_name": "Dividend Increase Announced", "tag": "Dividend Increase", "category": "Capital Allocation", "keywords": ["increased dividend", "raised dividend", "dividend hike"]},
    {"filter_name": "Dividend Cut Announced", "tag": "Dividend Cut", "category": "Capital Allocation", "keywords": ["cut dividend", "reduced dividend", "suspended dividend"]},
    {"filter_name": "Share Buyback Announced", "tag": "Buyback Announced", "category": "Capital Allocation", "keywords": ["share buyback", "stock repurchase", "repurchase program"]},
    {"filter_name": "Share Buyback Expansion", "tag": "Buyback Expanded", "category": "Capital Allocation", "keywords": ["expanded buyback", "increase repurchase"]},
    {"filter_name": "Share Buyback Suspension", "tag": "Buyback Suspended", "category": "Capital Allocation", "keywords": ["paused buyback", "suspended repurchase"]},
    {"filter_name": "Debt Issuance Announced", "tag": "Debt Issuance", "category": "Capital Allocation", "keywords": ["notes offering", "bond issuance", "selling bonds"]},
    {"filter_name": "Debt Reduction Announced", "tag": "Debt Reduction", "category": "Capital Allocation", "keywords": ["paying down debt", "debt repayment", "deleveraging"]},
    {"filter_name": "Equity Capital Raise", "tag": "Equity Raise", "category": "Capital Allocation", "keywords": ["stock offering", "secondary offering", "equity raise"]},
    {"filter_name": "Convertible Debt Issuance", "tag": "Convertible Debt", "category": "Capital Allocation", "keywords": ["convertible notes", "convertible bonds"]},
    {"filter_name": "Credit Facility Update", "tag": "Credit Facility", "category": "Capital Allocation", "keywords": ["credit facility", "revolving credit", "term loan"]},
    {"filter_name": "Leverage Target Change", "tag": "Leverage Change", "category": "Capital Allocation", "keywords": ["leverage ratio", "net debt target"]},

    # Legal & Regulatory
    {"filter_name": "SEC Filing Submitted", "tag": "SEC Filing", "category": "Legal & Regulatory", "keywords": ["10-k", "10-q", "8-k", "sec filing"]},
    {"filter_name": "SEC Investigation Announced", "tag": "SEC Investigation", "category": "Legal & Regulatory", "keywords": ["sec investigation", "sec probe", "wells notice"]},
    {"filter_name": "DOJ Investigation Announced", "tag": "DOJ Investigation", "category": "Legal & Regulatory", "keywords": ["doj investigation", "justice department probe"]},
    {"filter_name": "Lawsuit Filed", "tag": "Lawsuit", "category": "Legal & Regulatory", "keywords": ["lawsuit filed", "class action", "sued by", "litigation"]},
    {"filter_name": "Legal Settlement Reached", "tag": "Settlement", "category": "Legal & Regulatory", "keywords": ["settlement reached", "settle lawsuit", "agree to pay"]},
    {"filter_name": "Antitrust Action Initiated", "tag": "Antitrust Action", "category": "Legal & Regulatory", "keywords": ["antitrust", "monopoly", "anticompetitive"]},
    {"filter_name": "Regulatory Approval Granted", "tag": "Regulatory Approval", "category": "Legal & Regulatory", "keywords": ["fda approval", "approved by regulators", "cleared by"]},
    {"filter_name": "Regulatory Approval Denied", "tag": "Regulatory Rejection", "category": "Legal & Regulatory", "keywords": ["fda rejection", "blocked by regulators", "denied approval"]},
    {"filter_name": "Compliance Violation Disclosed", "tag": "Compliance Violation", "category": "Legal & Regulatory", "keywords": ["compliance breach", "regulatory violation"]},
    {"filter_name": "Fine or Penalty Issued", "tag": "Fine / Penalty", "category": "Legal & Regulatory", "keywords": ["fined", "penalty", "ordered to pay"]},
    {"filter_name": "Consent Decree Issued", "tag": "Consent Decree", "category": "Legal & Regulatory", "keywords": ["consent decree"]},
    {"filter_name": "Licensing Risk Identified", "tag": "Licensing Risk", "category": "Legal & Regulatory", "keywords": ["license dispute", "patent infringement"]},
    {"filter_name": "Sanctions Exposure Identified", "tag": "Sanctions Risk", "category": "Legal & Regulatory", "keywords": ["sanctions", "trade restrictions", "export ban"]},
]
